#pragma once
#undef WORLDBOUND

#undef PLAYERSPAWN

#undef PLAYERHEALTH
#undef NBRPLAYERLASER

#undef NBRALIENLASER

#undef AALIENHEALTH
#undef AALIENENERGY
#undef AALIENDIRECTION
#undef AALIENVELOCITY

#undef BALIENHEALTH
#undef BALIENENERGY
#undef BALIENDIRECTION
#undef BALIENVELOCITY